base/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'periodos', views.PeriodoCirculacionViewSet)

app_name = 'base'
urlpatterns = [

    url(r'^api/base/', include(router.urls)),
    url(r'^api/base/periodo/filter/$', views.PeriodoCirculacionFilterViewSet.as_view()),

]

circulacion/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('base.urls')),
    url(r'^', include('front.urls')),
    url(r'^', include('reporte.urls')),
]

front/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from front import views

app_name = 'front'
urlpatterns = [

	url(r'^$', views.index, name = 'index'),
	url(r'^login/$', views.the_login, name = 'login'),
	url(r'^consulta/$', views.consulta, name = 'consulta'),
    url(r'^consultas/json/$', views.consulta_json, name = 'consulta_json'),
    url(r'^tarjeta/$', views.tarjeta, name = 'tarjeta'),
    url(r'^tarjeta/(?P<id>.*)$', views.tarjeta, name = 'tarjeta'),
    url(r'^empresas/$', views.empresas, name = 'empresas'),
    url(r'^empresas/json/$', views.empresas_json, name = 'empresas_json'),
    url(r'^empresa/$', views.empresa, name = 'empresa'),
    url(r'^empresa/(?P<id>.*)$', views.empresa, name = 'empresa'),
    url(r'^resolucion/(?P<id_entidad>.*)/(?P<id>.*)$', views.resolucion_entidad, name = 'resolucion_entidad'),
    url(r'^resoluciones/(?P<entidad_id>.*)$', views.resoluciones_entidad, name = 'resoluciones_entidad'),
]

base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Entidad (models.Model):
	TIPO = (
		('E', 'EMPRESA'),
		('A', 'ASOCIACIÓN'),
	)
	tipo = models.CharField(max_length=1, choices=TIPO, default='E')
	ruc = models.IntegerField()
	razon_social = models.CharField(max_length=255)
	direccion = models.CharField(max_length=255)
	telefono = models.CharField(max_length=255)
	celular = models.CharField(max_length=255)

	def __str__(self):
		return self.razon_social

class PeriodoCirculacion(models.Model):
	TIPO = (
		('1', 'Mayores'),
		('2', 'Menores'),
	)
	razon_social = models.ForeignKey(Entidad)
	resolucion_autorizacion = models.CharField(max_length=255)
	nro_cupos = models.IntegerField()
	ruta_autorizada = models.CharField(max_length=255)
	representante_legal = models.CharField(max_length=255)
	vehiculo = models.CharField(max_length=1, choices=TIPO, default='1')
	fechainicio_periodo = models.DateField()
	fechafin_periodo = models.DateField()

	def __str__(self):
		return self.resolucion_autorizacion

import datetime
class TarjetaCirculacion(models.Model):
	resolucion_autorizacion = models.ForeignKey(PeriodoCirculacion)
	propietario = models.CharField(max_length=255)
	placa = models.CharField(max_length=255)
	clase = models.CharField(max_length=255)
	marca = models.CharField(max_length=255)
	anio_fabricacion = models.IntegerField()
	modelo = models.CharField(max_length=255)
	combustible = models.CharField(max_length=255)
	nro_ruta = models.IntegerField()
	color = models.CharField(max_length=255)
	cilindro = models.CharField(max_length=255)
	ruedas = models.IntegerField()
	nro_motor = models.CharField(max_length=255)
	nro_serie = models.CharField(max_length=255)
	pasajeros = models.IntegerField()
	asientos = models.IntegerField()
	peso_seco = models.IntegerField()
	peso_bruto = models.IntegerField()
	frecuencia = models.CharField(max_length=255)
	origen = models.CharField(max_length=255)
	poliza_seguro = models.CharField(max_length=255)
	fecha_expedicion = models.DateField()
	fecha = models.DateField()

	class Meta:
		verbose_name_plural='Tarjetas'

class Autoridad(models.Model):
    nombre_autoridad = models.CharField(max_length=255)
    fecha_inicio_autoridad = models.DateField()
    fecha_inicio_autoridad = models.DateField()
    firma_autoridad = models.ImageField(upload_to='firmas_autoridad', max_length=100)
    activo = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='Autoridades'

    def __str__(self):
        return  self.nombre_autoridad

base/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from serializers import PeriodoCirculacionSerializer
from rest_framework import viewsets, generics
from base.models import PeriodoCirculacion

from django.shortcuts import render

class PeriodoCirculacionViewSet(viewsets.ModelViewSet):
    queryset = PeriodoCirculacion.objects.all()
    serializer_class = PeriodoCirculacionSerializer

class PeriodoCirculacionFilterViewSet(generics.ListAPIView):
    serializer_class = PeriodoCirculacionSerializer

    def get_queryset(self):
        queryset = PeriodoCirculacion.objects.all()
        term = self.request.query_params.get('term', None)

        if term is not None:
            queryset = queryset.filter(razon_social__razon_social__icontains = term)
        return queryset

front/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from base.models import *
from base.forms import EntidadForm, PeriodoCirculacionForm, TarjetaCirculacionForm

from front.utils import crear_enlace, timestamp_a_fecha

from collections import OrderedDict
import json
# Create your views here.

def the_login(request):
    if(request.user.is_authenticated()):
        return HttpResponseRedirect(reverse('front:consulta'))

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('front:consulta'))
            else:
                messages.warning(request, 'El usuario no está activo.')
        else:
            messages.warning(request, 'Revise el usuario o la contraseña.')
        

    return render(request, 'front/login.html')

def consulta(request):
    return render(request, 'front/consulta-lista.html')

def consulta_json(request):
    filters = []
    cols = []
    for k in request.GET:
        if 'filter[' in k:
            filters.append(k)
        if 'column[' in k:
            cols.append(k)

    size = int(request.GET.get('size'))
    page = int(request.GET.get('page'))

    limit = page * size
    offset = limit + size

    data = {
        'headers': [
            'Resolucion', 'Propietario', 'Placa', 'Clase', 'Marca', 'Fabricacion', 'Modelo','Ruta','Pasajeros','Poliza','Fecha Exp','Fecha' 'Acciones'
        ]

    }

    tarjetas = TarjetaCirculacion.objects.all().order_by('-pk')

    if 'filter[0]' in filters:
        tarjetas = tarjetas.filter(resolucion_autorizacion__resolucion_autorizacion__contains = request.GET.get('filter[0]'))

    if 'filter[1]' in filters:
        tarjetas = tarjetas.filter(propietario__icontains = request.GET.get('filter[1]'))

    if 'filter[2]' in filters:
        tarjetas = tarjetas.filter(placa__icontains = request.GET.get('filter[2]'))

    if 'filter[3]' in filters:
        tarjetas = tarjetas.filter(clase__icontains = request.GET.get('filter[3]'))

    if 'filter[4]' in filters:
        tarjetas = tarjetas.filter(marca = request.GET.get('filter[4]'))

    if 'filter[5]' in filters:
        tarjetas = tarjetas.filter(fabricacion = request.GET.get('filter[5]'))

    if 'filter[6]' in filters:
        tarjetas = tarjetas.filter(modelo = request.GET.get('filter[6]'))

    if 'filter[7]' in filters:
        tarjetas = tarjetas.filter(ruta = request.GET.get('filter[8]'))

    if 'filter[8]' in filters:
        tarjetas = tarjetas.filter(pasajeros = request.GET.get('filter[10]'))

    if 'filter[9]' in filters:
        tarjetas = tarjetas.filter(poliza = request.GET.get('filter[12]'))

    if 'filter[10]' in filters:
        str_fecha = request.GET.get('filter[13]')
        if str_fecha[:2] == '<=':
            fecha = str_fecha[2:12]
            tarjetas = tarjetas.distinct().filter(fecha_expedicion__lte = timestamp_a_fecha(fecha, '%Y-%m-%d'))
        elif str_fecha[:2] == '>=':
            fecha = str_fecha[2:12]
            tarjetas = tarjetas.distinct().filter(fecha_expedicion__gte = timestamp_a_fecha(fecha, '%Y-%m-%d'))
        else:
            inicial = timestamp_a_fecha(str_fecha[:10], '%Y-%m-%d')
            final = timestamp_a_fecha(str_fecha[-13:][:10], '%Y-%m-%d')
            tarjetas = tarjetas.distinct().filter(fecha_expedicion__range = (inicial, final))

    if 'filter[11]' in filters:
        str_fecha = request.GET.get('filter[14]')
        if str_fecha[:2] == '<=':
            fecha = str_fecha[2:12]
            tarjetas = tarjetas.distinct().filter(fecha__lte = timestamp_a_fecha(fecha, '%Y-%m-%d'))
        elif str_fecha[:2] == '>=':
            fecha = str_fecha[2:12]
            tarjetas = tarjetas.distinct().filter(fecha__gte = timestamp_a_fecha(fecha, '%Y-%m-%d'))
        else:
            inicial = timestamp_a_fecha(str_fecha[:10], '%Y-%m-%d')
            final = timestamp_a_fecha(str_fecha[-13:][:10], '%Y-%m-%d')
            tarjetas = tarjetas.distinct().filter(fecha__range = (inicial, final))
    

    if 'column[0]' in cols:
        signo = '' if request.GET.get('column[0]') == '0' else '-'
        tarjetas = tarjetas.order_by('%sresolucion_autorizacion' % signo)

    if 'column[1]' in cols:
        signo = '' if request.GET.get('column[1]') == '0' else '-'
        tarjetas = tarjetas.order_by('%spropietario' % signo)

    if 'column[2]' in cols:
        signo = '' if request.GET.get('column[2]') == '0' else '-'
        tarjetas = tarjetas.order_by('%splaca' % signo)

    if 'column[3]' in cols:
        signo = '' if request.GET.get('column[3]') == '0' else '-'
        tarjetas = tarjetas.order_by('%sclase' % signo)

    if 'column[4]' in cols:
        signo = '' if request.GET.get('column[4]') == '0' else '-'
        tarjetas = tarjetas.order_by('%smarca' % signo)

    if 'column[5]' in cols:
        signo = '' if request.GET.get('column[5]') == '0' else '-'
        tarjetas = tarjetas.order_by('%sfabricacion' % signo)

    if 'column[6]' in cols:
        signo = '' if request.GET.get('column[6]') == '0' else '-'
        tarjetas = tarjetas.order_by('%smodelo' % signo)

    if 'column[7]' in cols:
        signo = '' if request.GET.get('column[8]') == '0' else '-'
        tarjetas = tarjetas.order_by('%sruta' % signo)

    if 'column[8]' in cols:
        signo = '' if request.GET.get('column[10]') == '0' else '-'
        tarjetas = tarjetas.order_by('%spasajeros' % signo)

    if 'column[9]' in cols:
        signo = '' if request.GET.get('column[12]') == '0' else '-'
        tarjetas = tarjetas.order_by('%spoliza' % signo)

    if 'column[10]' in cols:
        signo = '' if request.GET.get('column[13]') == '0' else '-'
        tarjetas = tarjetas.order_by('%sfecha_expedicion' % signo)

    if 'column[11]' in cols:
        signo = '' if request.GET.get('column[14]') == '0' else '-'
        tarjetas = tarjetas.order_by('%sfecha' % signo)

    total_rows = tarjetas.count()

    tarjetas = tarjetas[limit:offset]

    rows = []
    for tarjeta in tarjetas:

        links = crear_enlace(reverse('front:tarjeta', args=[tarjeta.id]), 'success', 'Ver o Editar', 'edit')
        links += crear_enlace(reverse('reporte:tarjeta_print', args=[tarjeta.id]), 'success', 'Imprimir', 'print')
       # -*-links += crear_enlace(reverse('reporte:licencia_print2', args=[licencia.id]), 'info', 'Imprimir Reverso', 'print')

        if tarjeta.fecha_expedicion is None:
            fecha = 'Sin datos'
        else:
            fecha = tarjeta.fecha_expedicion.strftime('%d/%m/%Y')

        if tarjeta.fecha is None:
            fecha2 = 'Sin datos'
        else:
            fecha2 = tarjeta.fecha.strftime('%d/%m/%Y')


        obj = OrderedDict({
            '0': tarjeta.resolucion_autorizacion.resolucion_autorizacion,
            '1': tarjeta.propietario,
            '2': tarjeta.placa,
            '3': tarjeta.clase,
            '4': tarjeta.marca,
            '5': tarjeta.anio_fabricacion,
            '6': tarjeta.modelo,
            '7': tarjeta.nro_ruta,
            '8': tarjeta.pasajeros,
            '9': tarjeta.poliza_seguro,
            '10': fecha,
            '11': fecha2,
            '12': links,
        })
        rows.append(obj)

    data['rows'] = rows
    data['total_rows'] = total_rows

    return HttpResponse(json.dumps(data), content_type = "application/json")

@login_required
def index(request):
    return render(request, 'front/index.html')

@login_required
def tarjeta(request, id=None):
    l=None
    if id is not None:
        l=TarjetaCirculacion.objects.get(id=id)
    if request.method == 'POST':
        if l is None:
            form = TarjetaCirculacionForm(request.POST)
        else:
            form = TarjetaCirculacionForm(request.POST,instance=l)
        if form.is_valid():
            tarjeta = form.save(commit=False)
            resolucion_autorizacion = request.POST.get('resolucion')
            resolucion_autorizacion = PeriodoCirculacion.objects.get(id = resolucion_autorizacion)
            tarjeta.resolucion_autorizacion = resolucion_autorizacion
            tarjeta.save()
            if l is None:
                messages.warning(request, 'Se ha creado una tarjeta.')
            else:
                messages.warning(request, 'Se ha Actualizado una tarjeta.')
            return HttpResponseRedirect(reverse('front:consulta'))
        else:
            print form.errors
            return render(request, 'front/tarjeta.html', {'form': form})
    else:
        if l is None:
            form = TarjetaCirculacionForm()   
        else:
            form = TarjetaCirculacionForm(instance=l)
        return render(request, 'front/tarjeta.html', {'form': form})

@login_required
def empresas(request):
    return render(request, 'front/entidad-lista.html')

def empresas_json(request):
    filters = []
    cols = []
    for k in request.GET:
        if 'filter[' in k:
            filters.append(k)
        if 'column[' in k:
            cols.append(k)

    size = int(request.GET.get('size'))
    page = int(request.GET.get('page'))

    limit = page * size
    offset = limit + size

    data = {
        'headers': [
            'Tipo', 'Ruc', 'Razon Social', 'Direccion', 'Telefono','Celular', 'Acciones'
        ]

    }

    empresas = Entidad.objects.all().order_by('-pk')

    if 'filter[0]' in filters:
        tipo_reverse = dict((v,k) for k, v in Entidad.TIPO)
        empresas = empresas.filter(tipo = tipo_reverse[request.GET.get('filter[0]')])

front/templates/front/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/flatly/bootstrap.min.css" integrity="sha256-r1WijW/SNMgOwk5LDk7QRHr6oVYYbYWMw/1kOXfYJfg=" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/redmond/jquery-ui.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css %}{% endblock css %}
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'front:index' %}">Licencias de Circulacion</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'front:consulta' %}">Consultas</a></li>
                    <li><a href="{% url 'front:empresas' %}">Empresas</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container{% block fluid %}{% endblock fluid %}">
        <div id="messages">
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{% if message.tags %}{% if message.tags == 'error'%}danger{% else %}{{ message.tags }}{% endif %}{% endif %} animated bounceIn">
            <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
            <p>{{ message }}</p>
          </div>
          {% endfor %}
        {% endif %}
        </div>
        {% block content %}
            
        {% endblock content %}
    </div>
    <hr>
    <footer id="footer">
      <div class="container">
        <p class="text-muted credit text-right">
          
        </p>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static "front/js/scripts.js" %}"></script>
    {% block js %}{% endblock js %}
</body>
</html>

front/templates/front/entidad-lista.html
{% extends "front/base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Empresas
                <span class="small pull-right">
                    <a href="{% url 'front:empresa' %}" class="btn btn-primary btn-sm">Crear Empresa</a>
                    <button class="btn btn-default btn-sm reset"><i class="fa fa-filter"></i> Quitar Filtros</button>
                </span>
            </h1>
        </div>
    </div>
    <table class="table table bordered table-striped" id="empresas">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Ruc</th>
                <th>Razon Social</th>
                <th>Direccion</th>
                <th>Telefono</th>
                <th>Celular</th>
                <th class="filter-false sorter-false">Acciones</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
        <tfoot>
            <tr>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
            </tr>
            <tr>
              <th colspan="7" class="ts-pager form-horizontal">
                <button type="button" class="btn btn-xs first"><i class="icon-step-backward glyphicon glyphicon-step-backward"></i></button>
                <button type="button" class="btn btn-xs prev"><i class="icon-arrow-left glyphicon glyphicon-backward"></i></button>
                <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
                <button type="button" class="btn btn-xs next"><i class="icon-arrow-right glyphicon glyphicon-forward"></i></button>
                <button type="button" class="btn btn-xs last"><i class="icon-step-forward glyphicon glyphicon-step-forward"></i></button>
                <select class="pagesize input-mini" title="Elementos a mostrar ">
                  <option selected="selected" value="10">10</option>
                  <option value="20">20</option>
                  <option value="30">30</option>
                  <option value="40">40</option>
                  <option value="9999">Todos</option>
                </select>
                <select class="pagenum input-mini" title="Número de página"></select>
              </th>
            </tr>
      </tfoot>
    </table>
{% endblock content %}

{% block title %}Empresas{% endblock title %}


{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.0/js/jquery.tablesorter.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.0/js/jquery.tablesorter.widgets.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.0/js/widgets/widget-filter-formatter-jui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.0/js/extras/jquery.tablesorter.pager.min.js"></script>
<script src="{% static "front/js/empresas.js" %}"></script>
{% endblock js %}

{% block css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.28.0/css/theme.bootstrap.min.css">
{% endblock css %}

front/templates/front/entidad.html
{% extends "front/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if form.instance.id != None %}
                <h1>Editar Empresa
                    <span class="small pull-right">
                        <a href="{% url 'front:empresa' %}" class="btn btn-primary">Crear Empresa</a>
                        <a href="{% url 'front:empresas' %}" class="btn btn-primary">Ver todas las Empresas</a>
                    </span>
                </h1>
            {% else %}
                <h1>Crear Empresa
                <span class="small pull-right">
                    <a href="{% url 'front:empresas' %}" class="btn btn-primary">Ver todas las Empresa</a>
                </span>
            </h1>
            {% endif %}
            <form action="" method="post" enctype="multipart/form-data">
                {% for field in  form %}
                    <div class="form-group">
                        <label for="">{{ field.label }}:</label>
                        {{ field }}
                        {% if field.errors %}
                            {{ field.errors }}
                        {% endif %}
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-save"></i> Guardar</button>
            </form>
        </div>
    </div>

{% endblock content %}

{% block title %}Listas{% endblock title %}

front/templates/front/index.html
{% extends 'front/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="intro">
            <h3 class="text-success">Bienvenido</h3>
        </div>
    </div>
</div>
{% endblock %}

{% block title %}Bienvenido{% endblock %}

front/templates/front/lista-resoluciones.html
{% extends "front/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Consultar Resoluciones
                <span class="small pull-right">
                    <a href="{% url 'front:resolucion_entidad' id_entidad=entidad.id id=0 %}" class="btn btn-primary">Crear Resolucion</a>
                </span>
            </h1>
        </div>
    </div>
    <ul class="list-group">
        <li class="list-group-item text-center"><strong>Consulta de la Entidad: </strong> {{ persona }}</li>
        <li class="list-group-item text-center"><strong>Razon Social: </strong> {{ entidad.razon_social }}</li>
        <li class="list-group-item text-center"><strong>Direccion: </strong> {{ entidad.direccion }}</li>
        <li class="list-group-item text-center"><strong>Telefono: </strong> {{ entidad.telefono }}</li>
    </ul>
    <table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Razon Social</th>
            <th>Resolucion N°</th>
            <th>N° Cupos</th>
            <th>Ruta</th>
            <th>Representante</th>
            <th>Vehiculo</th>
            <th>Fecha Inicio</th>
            <th>Fecha Fin</th>
        </tr>
    </thead>
    <tbody>
        {% for resolucion in entidad.periodocirculacion_set.all %}
            <tr>
                <td>{{ resolucion.razon_social }}</td>
                <td>{{ resolucion.resolucion_autorizacion }}</td>
                <td>{{ resolucion.nro_cupos }}</td>
                <td>{{ resolucion.ruta_autorizada }}</td>
                <td>{{ resolucion.representante_legal }}</td>
                <td>{{ resolucion.vehiculo }}</td>
                <td>{{ resolucion.fechainicio_periodo }}</td>
                <td>{{ resolucion.fechafin_periodo }}</td>
                <td><a href="{% url 'front:resolucion_entidad' id_entidad=entidad.id id=resolucion.id %}">Editar</a></td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="12" class="text-center">No existen datos</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

{% block title %}Resoluciones{% endblock title %}

front/templates/front/resolucion.html
{% extends "front/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if form.instance.id != None %}
                <h1>Editar Resolucion para {{entidad}} ({{entidad.razon_social}})
                    <span class="small pull-right">
                        <a href="{% url 'front:resoluciones_entidad' entidad.id %}" class="btn btn-primary">Ver todas sus Resoluciones</a>
                        <a href="{% url 'front:resolucion_entidad' id_entidad=entidad.id id=0 %}" class="btn btn-primary">Crear nueva Resolucion</a>
                    </span>
                </h1>
            {% else %}
                <h1>Crear Resoluciones para {{entidad}} ({{entidad.razon_social}})
                    <span class="small pull-right">
                        <a href="{% url 'front:resoluciones_entidad' entidad.id %}" class="btn btn-primary">Ver todas sus Resoluciones</a>
                    </span>
                </h1>
            {% endif %}
            <form action="" method="post">
                {% for field in  form %}
                    <div class="form-group">
                        <label for="">{{ field.label }}:</label>
                        {{ field }}
                        {% if field.errors %}
                            {{ field.errors }}
                        {% endif %}
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-save"></i> Guardar</button>
            </form>
        </div>
    </div>

{% endblock content %}

{% block title %}Resoluciones{% endblock title %}